name: MSBuild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64
        
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64
          
    - name: Config
      working-directory: valve
      shell: cmd
      run: fp_config.bat

    - name: Build
      working-directory: valve
      shell: cmd
      run: jom\\\jom.exe
      
    - name: Install
      working-directory: valve
      shell: cmd
      run: jom\\\jom.exe install
